apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: application
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  labels:
    name: application
spec:
  replicas: 1
  selector:
    matchLabels:
      service: application
  template:
    metadata:
      labels:
        service: application
    spec:
      containers:
      - name: application
        image: 021433698475.dkr.ecr.us-east-1.amazonaws.com/project3/udacity:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        envFrom:
        - configMapRef:
            name: postgres-configmap
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-db-postgresql
              key: postgres-password
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
      restartPolicy: Always